### ISSUE TITLE
error about KINgaroo

### ISSUE THREAD

**Issue by triangbyam** [DivyaratanPopli/Kinship_Inference#10]
Hi!
I have tried to use the software KIN to estimate the relationship of ancient individual, and prepared the bedfile and bamfiles as require, but I have met some troubles in running KINgaroo, the reported error as follow: 

Finished indexing, sorting and splitting bamfiles...
Merging all chromosomes..
Creating input files from chromosome 1...
Creating input files from chromosome 2...
Creating input files from chromosome 3...
Creating input files from chromosome 4...
Creating input files from chromosome 5...
Creating input files from chromosome 6...
Creating input files from chromosome 7...
Creating input files from chromosome 8...
Creating input files from chromosome 9...
Creating input files from chromosome 10...
Creating input files from chromosome 11...
Creating input files from chromosome 12...
Creating input files from chromosome 13...
Creating input files from chromosome 14...
Creating input files from chromosome 15...
Creating input files from chromosome 16...
Creating input files from chromosome 17...
Creating input files from chromosome 18...
Creating input files from chromosome 19...
Creating input files from chromosome 20...
Creating input files from chromosome 21...
Creating input files from chromosome 22...
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/Users/fanzhang/anaconda3/lib/python3.10/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/Users/fanzhang/anaconda3/lib/python3.10/site-packages/KINgaroo/KINgaroo_scripts/helpers.py", line 139, in get_merged_chrm
    diffs_list = findDiff(inds=probs_list, posall=pos_list)
  File "/Users/fanzhang/anaconda3/lib/python3.10/site-packages/KINgaroo/KINgaroo_scripts/input_preparation_functions.py", line 121, in findDiff
    inds[inds==-9]=np.nan
ValueError: cannot convert float NaN to integer
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/fanzhang/anaconda3/bin/KINgaroo", line 8, in <module>
    sys.exit(__main__.main())
  File "/Users/fanzhang/anaconda3/lib/python3.10/site-packages/KINgaroo/__main__.py", line 104, in main
    libraries, listf, dwins, twins, id_dwins, id_twins, chrmlist = hel.pipeline1(targetsfile = args.target_location,
  File "/Users/fanzhang/anaconda3/lib/python3.10/site-packages/KINgaroo/KINgaroo_scripts/helpers.py", line 330, in pipeline1
    dwins,twins,id_dwins,id_twins, chrmlist = parallel_mergedchrm(libraries=libraries, totalch=chrmf, interval=interval, cores=cores)
  File "/Users/fanzhang/anaconda3/lib/python3.10/site-packages/KINgaroo/KINgaroo_scripts/helpers.py", line 154, in parallel_mergedchrm
    allf = [p.get() for p in res]
  File "/Users/fanzhang/anaconda3/lib/python3.10/site-packages/KINgaroo/KINgaroo_scripts/helpers.py", line 154, in <listcomp>
    allf = [p.get() for p in res]
  File "/Users/fanzhang/anaconda3/lib/python3.10/multiprocessing/pool.py", line 774, in get
    raise self._value
ValueError: cannot convert float NaN to integer

Is there any way to address this issue?
Thanks!

**Comment by DivyaratanPopli** [comment]
Hi, I think you are using an old version. Also, you can use the test function to see if there is an issue with the format of input files.
