### ISSUE TITLE
problems about KINgaroo installation

### ISSUE THREAD

**Issue by zhangjsyeah** [DivyaratanPopli/Kinship_Inference#2]
Dear professor：
The KINgaroo was installed successfully, but When I run the "KINgaroo -bam /trimBam -bed /bed -T /Bam_list.txt -cnt 0"  command it gives the following error : what should i do with it？Thank you very much
` File "/.conda/envs/aDNA/lib/python3.10/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/.conda/envs/aDNA/bin/KINgaroo", line 8, in <module>
    sys.exit(__main__.main())
  File "/.conda/envs/aDNA/lib/python3.10/site-packages/KINgaroo/__main__.py", line 91, in main
    libraries, listf, dwins, twins, id_dwins, id_twins, chrmlist = hel.pipeline1(targetsfile = args.target_location,
  File "/.conda/envs/aDNA/lib/python3.10/site-packages/KINgaroo/KINgaroo_scripts/helpers.py", line 315, in pipeline1
    dwins,twins,id_dwins,id_twins, chrmlist = parallel_mergedchrm(libraries=libraries, totalch=chrmf, interval=interval, cores=cores)
  File "/.conda/envs/aDNA/lib/python3.10/site-packages/KINgaroo/KINgaroo_scripts/helpers.py", line 139, in parallel_mergedchrm
    allf = [p.get() for p in res]
  File "/.conda/envs/aDNA/lib/python3.10/site-packages/KINgaroo/KINgaroo_scripts/helpers.py", line 139, in <listcomp>
    allf = [p.get() for p in res]
  File "/.conda/envs/aDNA/lib/python3.10/multiprocessing/pool.py", line 771, in get
    raise self._value
FileNotFoundError: [Errno 2] No such file or directory: 'hapProbs/hapProbs_chrm1_probs.csv'`

**Comment by DivyaratanPopli** [comment]
Hi, it looks like the input files may not be in the right format. You can check this in the README.md (https://github.com/DivyaratanPopli/Kinship_Inference/blob/main/README.md), and compare to the example files.
