### ISSUE TITLE
error about 'KINgaroo -h'

### ISSUE THREAD

**Issue by Pudding-Q** [DivyaratanPopli/Kinship_Inference#3]
Dear professor：
  The KINgaroo has been installed with 'pip3 install /home/software/Kinship_Inference-main/pypackage/kingaroo', however when I run 'KINgaroo -h',the command line shows that:

'Traceback (most recent call last):
  File "/home/miniconda3/envs/DNAtest/bin/KINgaroo", line 8, in <module>
    sys.exit(__main__.main())
  File "/home/miniconda3/envs/DNAtest/lib/python3.8/site-packages/KINgaroo/__main__.py", line 64, in main
    args = cli()
  File "/home/miniconda3/envs/DNAtest/lib/python3.8/site-packages/KINgaroo/__main__.py", line 61, in cli
    return parser.parse_args()
  File "/home/miniconda3/envs/DNAtest/lib/python3.8/argparse.py", line 1768, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "/home/miniconda3/envs/DNAtest/lib/python3.8/argparse.py", line 1800, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/home/miniconda3/envs/DNAtest/lib/python3.8/argparse.py", line 2006, in _parse_known_args
    start_index = consume_optional(start_index)
  File "/home/miniconda3/envs/DNAtest/lib/python3.8/argparse.py", line 1946, in consume_optional
    take_action(action, args, option_string)
  File "/home/miniconda3/envs/DNAtest/lib/python3.8/argparse.py", line 1874, in take_action
    action(self, namespace, argument_values, option_string)
  File "/home/miniconda3/envs/DNAtest/lib/python3.8/argparse.py", line 1044, in __call__
    parser.print_help()
  File "/home/miniconda3/envs/DNAtest/lib/python3.8/argparse.py", line 2494, in print_help
    self._print_message(self.format_help(), file)
  File "/home/miniconda3/envs/DNAtest/lib/python3.8/argparse.py", line 2478, in format_help
    return formatter.format_help()
  File "/home/miniconda3/envs/DNAtest/lib/python3.8/argparse.py", line 282, in format_help
    help = self._root_section.format_help()
  File "/home/miniconda3/envs/DNAtest/lib/python3.8/argparse.py", line 213, in format_help
    item_help = join([func(*args) for func, args in self.items])
  File "/home/miniconda3/envs/DNAtest/lib/python3.8/argparse.py", line 213, in <listcomp>
    item_help = join([func(*args) for func, args in self.items])
  File "/home/miniconda3/envs/DNAtest/lib/python3.8/argparse.py", line 337, in _format_usage
    assert ' '.join(opt_parts) == opt_usage
AssertionError'

  Could you please tell me how to deal with it? Thank you very much!

**Comment by DivyaratanPopli** [comment]
Hi, can you type only "KINgaroo" on the terminal, and tell me what you get?

**Comment by Pudding-Q** [comment]
When I  type "KINgaroo" only , it shows that:
"Traceback (most recent call last):
  File "/home/miniconda3/envs/DNAtest/bin/KINgaroo", line 8, in <module>
    sys.exit(__main__.main())
  File "/home/miniconda3/envs/DNAtest/lib/python3.8/site-packages/KINgaroo/__main__.py", line 64, in main
    args = cli()
  File "/home/miniconda3/envs/DNAtest/lib/python3.8/site-packages/KINgaroo/__main__.py", line 61, in cli
    return parser.parse_args()
  File "/home/miniconda3/envs/DNAtest/lib/python3.8/argparse.py", line 1768, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "/home/miniconda3/envs/DNAtest/lib/python3.8/argparse.py", line 1800, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/home/miniconda3/envs/DNAtest/lib/python3.8/argparse.py", line 2034, in _parse_known_args
    self.error(_('the following arguments are required: %s') %
  File "/home/miniconda3/envs/DNAtest/lib/python3.8/argparse.py", line 2519, in error
    self.print_usage(_sys.stderr)
  File "/home/miniconda3/envs/DNAtest/lib/python3.8/argparse.py", line 2489, in print_usage
    self._print_message(self.format_usage(), file)
  File "/home/miniconda3/envs/DNAtest/lib/python3.8/argparse.py", line 2455, in format_usage
    return formatter.format_help()
  File "/home/miniconda3/envs/DNAtest/lib/python3.8/argparse.py", line 282, in format_help
    help = self._root_section.format_help()
  File "/home/miniconda3/envs/DNAtest/lib/python3.8/argparse.py", line 213, in format_help
    item_help = join([func(*args) for func, args in self.items])
  File "/home/miniconda3/envs/DNAtest/lib/python3.8/argparse.py", line 213, in <listcomp>
    item_help = join([func(*args) for func, args in self.items])
  File "/home/miniconda3/envs/DNAtest/lib/python3.8/argparse.py", line 337, in _format_usage
    assert ' '.join(opt_parts) == opt_usage
AssertionError"

**Comment by DivyaratanPopli** [comment]
OK so it gives the same error related to argparse. Can you send me the messages printed on the screen when you install KINgaroo?

**Comment by Pudding-Q** [comment]
Hi,I have been successfully built KINgaroo with "pip3 install /data/home/qyouyang/software/Kinship_Inference-main/pypackage/kingaroo".When I install KINgaroo,the messages are as follows:（as .png1)
![1](https://user-images.githubusercontent.com/101164181/187842515-cf3632f2-c3e1-4824-9d4b-e079afff7fe7.png)

When I type "KINgaroo -h",it shows :（as .png2)
![2](https://user-images.githubusercontent.com/101164181/187842571-352c2c39-03f6-47b7-8d91-939639b7735f.png)

However,when I try to run the software with "KINgaroo -bam bamRawdata/ -bed bedfile.bed -T targets.txt -cnt 0",there is still some error :（as .png3-5)
![3](https://user-images.githubusercontent.com/101164181/187842678-752b99f3-45b6-4902-b3a5-8ef383931f52.png)
![4](https://user-images.githubusercontent.com/101164181/187842715-794c8a30-facf-4a94-89fb-eba9c567782d.png)
![5](https://user-images.githubusercontent.com/101164181/187842790-d390a550-53a1-4536-855d-75d3573a74dd.png)

**Comment by DivyaratanPopli** [comment]
Hi, it looks like the script is unable to create files. Usually this this happens when the input files are not in correct format. Can you go through README.md (https://github.com/DivyaratanPopli/Kinship_Inference/blob/main/README.md) and check that your input files are in the correct form, you can compare them to the example files shown in README.md.

**Comment by Pudding-Q** [comment]
Hi，I have checked the format according to the README.md. But I have no idea about the error.Here are the screenshots of the input files:
bam:
![1](https://user-images.githubusercontent.com/101164181/187876650-1414349b-ba93-448f-ad25-7e644efa1a39.png)

bedfile.bed:
![2](https://user-images.githubusercontent.com/101164181/187876696-ae013561-bf18-4039-ab54-a69b3b8f68dc.png)

targets.txt
![3](https://user-images.githubusercontent.com/101164181/187876786-c3eba28c-12a0-49fd-bce7-6ac4d491320f.png)


By the way, we don't have "bam-rmdup"（Kinship_Inference/KINgaroo_snakemake_version/Snakefile） in our server. Do you think  installing biohazard-tools(https://github.com/mpieva/biohazard-tools) would help solve this problem?

**Comment by DivyaratanPopli** [comment]
Hi, You are right that bam-rmdup may be causing this problem. I have now removed this function. Can you clone the repository again, and reinstall kingaroo?
 
In case it still gives you a problem, you can run a test as:
KINgaroo -bam bamfiles/ -bed bedfile.bed -T targets.txt -cnt 0 -test 1
It will print a message that files are OK, if it can read the input files, and also write some output files.

**Comment by Pudding-Q** [comment]
Hi, I clone the new repository  "Kinship_Inference-main-2", and reinstall kingaroo. The error I met the day before yesterday shows again:
![1](https://user-images.githubusercontent.com/101164181/188115082-de1f1876-8d24-49d7-a821-e098ebab2bc2.png)
![2](https://user-images.githubusercontent.com/101164181/188115126-a9449329-789a-4e75-a39d-fab3c111ae5a.png)
Then, I run a test as you suggested，it shows that the input files are OK. I have checked other output files and found no problems
![截屏2022-09-02 15 59 18](https://user-images.githubusercontent.com/101164181/188116146-f3f97c4f-2bc2-4290-9288-03853c15f76b.png)
![6](https://user-images.githubusercontent.com/101164181/188116196-c9b555c6-6d87-4afa-b719-c1d6968eef29.png)

While I try to run the the software , another error occurred:

![4](https://user-images.githubusercontent.com/101164181/188116652-f63f0bb1-328f-47a8-b31d-0a02f3e377cb.png)
![5](https://user-images.githubusercontent.com/101164181/188116700-c12175ab-eaf6-4dba-8156-b9de3967c0ef.png)

**Comment by DivyaratanPopli** [comment]
Hi, so at least the scripts are running now, and error is from an internal function. I have included a print statement in this function so I can see what the problem is. Can you clone the repository again and run it, and tell me what is printed on the screen before the error?
Also, it is strange that KINgaroo -h gives you error. Are you using the conda environment as described in the README.md?

**Comment by Pudding-Q** [comment]
Hi,I created the conda environment by "conda create -n my_conda_env python=3.8 scipy=1.8.0 numpy=1.21.1 pandas=1.3.1 numba=0.55.1 pysam=0.19.0 pybedtools=0.9.0".In this way ,I have successfully installed ”Kinship_Inferenc-main“,but there was a problem about "bam-rmdup".
And now, I  clone the new repository,run it by：“KINgaroo -bam BAM-q30/ -bed bedfile.bed -T targets.txt -cnt 0”.Here is the message printed on the screen before the error:
![截屏2022-09-06 13 55 52](https://user-images.githubusercontent.com/101164181/188557561-c5bba5cf-3985-479d-a7b2-3f959f6a2a67.png)

**Comment by DivyaratanPopli** [comment]
Hi, are you using only one chromosome? It looks like the script is complaining because your bamfiles do not have any data. Can you try with all chromosomes?
You mentioned in your initial message that KINgaroo -h does not work, but it worked fine later (as .png2). What did you change to make it work? It must be some change in local environment.
