### ISSUE TITLE
error occur in KINgaroo

### ISSUE THREAD

**Issue by xiaomiyang36** [DivyaratanPopli/Kinship_Inference#8]
Hi !
I have tried to use the software KIN to estimate the kinship cofficient of ancient individual, and prepared the bedfile and bamfiles as require, but I have met some troubles in running KINgaroo, the reported error as follow:

> multiprocessing.pool.RemoteTraceback: 

"""
`Traceback (most recent call last):
  File "/home/administrator/miniconda3/lib/python3.9/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/administrator/miniconda3/lib/python3.9/site-packages/KINgaroo/KINgaroo_scripts/helpers.py", line 154, in get_merged_chrm
    diffs_list = findDiff(inds=probs_list, posall=pos_list)
  File "/home/administrator/miniconda3/lib/python3.9/site-packages/KINgaroo/KINgaroo_scripts/input_preparation_functions.py", line 124, in findDiff
    diff0=(np.vstack(inds[:,0]) * (1-inds)) + ((1-np.vstack(inds[:,0])) * inds)
  File "<__array_function__ internals>", line 180, in vstack
  File "/home/administrator/miniconda3/lib/python3.9/site-packages/numpy/core/shape_base.py", line 282, in vstack
    return _nx.concatenate(arrs, 0)
  File "<__array_function__ internals>", line 180, in concatenate
ValueError: need at least one array to concatenate
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/administrator/miniconda3/bin/KINgaroo", line 8, in <module>
    sys.exit(__main__.main())
  File "/home/administrator/miniconda3/lib/python3.9/site-packages/KINgaroo/__main__.py", line 120, in main
    libraries, listf, dwins, twins, id_dwins, id_twins, chrmlist = hel.pipeline1(targetsfile = args.target_location,
  File "/home/administrator/miniconda3/lib/python3.9/site-packages/KINgaroo/KINgaroo_scripts/helpers.py", line 354, in pipeline1
    dwins,twins,id_dwins,id_twins, chrmlist = parallel_mergedchrm(libraries=libraries, totalch=chrmf, interval=interval, cores=cores)
  File "/home/administrator/miniconda3/lib/python3.9/site-packages/KINgaroo/KINgaroo_scripts/helpers.py", line 174, in parallel_mergedchrm
    allf = [p.get() for p in res]
  File "/home/administrator/miniconda3/lib/python3.9/site-packages/KINgaroo/KINgaroo_scripts/helpers.py", line 174, in <listcomp>
    allf = [p.get() for p in res]
  File "/home/administrator/miniconda3/lib/python3.9/multiprocessing/pool.py", line 771, in get
    raise self._value
ValueError: Can not process input data. Please check all input files. In particular, bedfile and bamfiles should have chromosomes listed as 1,2,... and the bedfile should be tab-separated. Please check the README.md for example input files`
> 

Is there any way to address this issue?
Thanks!
Yang

**Comment by DivyaratanPopli** [comment]
Hi, the error suggests there is some issue with the input files: "Can not process input data. Please check all input files. In particular, bedfile and bamfiles should have chromosomes listed as 1,2,... and the bedfile should be tab-separated. Please check the README.md for example input files"

**Comment by xiaomiyang36** [comment]
We mapped the rawdata-fastaq to hs37d5 and generated bamfiles with chromosomes listed as 1,2,3,....，and the bedfile we used as follows: 
![image](https://user-images.githubusercontent.com/78222976/235034924-20a3d62a-3308-4ee0-8d75-3f5e14d37398.png)
 
The same error still reports~

**Comment by DivyaratanPopli** [comment]
Can you check if the bedfile is tab-separated?

**Comment by xiaomiyang36** [comment]
Thanks! This problem has been sovled already.
